defaults:
  background:
    colors:
    - '#E8F0FE'
    - '#F8FBFF'
    direction: 180
    type: linear
devices:
- iPhone 15 Pro Portrait
project:
  name: My Screenshot Project
  output_dir: Screenshots/Generated
screenshots:
- content:
  - color: '#8E4EC6'
    content: Beautiful App
    position:
    - 50%
    - 15%
    size: 48
    type: text
    weight: bold
  - color: '#1A73E8'
    content: Transform your workflow today
    position:
    - 50%
    - 25%
    size: 24
    type: text
  - asset: screenshots/home.png
    frame: true
    position:
    - 50%
    - 60%
    scale: 0.6
    type: image
  name: welcome_screen
- content:
  - color: '#8E4EC6'
    content: "\u2728 Amazing Features"
    position:
    - 50%
    - 10%
    size: 42
    type: text
    weight: bold
  - asset: screenshots/features.png
    frame: true
    position:
    - 50%
    - 65%
    scale: 0.5
    type: image
  name: features_screen
- content:
  - content: "\U0001F308 Gradient Magic"
    gradient:
      colors:
      - '#FF6B6B'
      - '#4ECDC4'
      - '#45B7D1'
      direction: 45
      type: linear
    position:
    - 50%
    - 15%
    size: 48
    type: text
    weight: bold
  - content: Beautiful gradients for stunning text
    gradient:
      center:
      - 50%
      - 50%
      colors:
      - '#667eea'
      - '#764ba2'
      radius: 70%
      type: radial
    position:
    - 50%
    - 25%
    size: 24
    type: text
  - content: Advanced Color Control
    gradient:
      colors:
      - '#f093fb'
      - '#f5576c'
      - '#4facfe'
      direction: 90
      positions:
      - 0.0
      - 0.3
      - 1.0
      type: linear
    position:
    - 50%
    - 35%
    size: 28
    stroke_color: '#333333'
    stroke_width: 2
    type: text
  - asset: screenshots/gradient_demo.png
    frame: true
    position:
    - 50%
    - 70%
    scale: 0.5
    type: image
  name: gradient_showcase
